version: 0.0
os: linux
files:
  - source: nginx/sites-default
    destination: /etc/nginx/sites-available/default
  - source: source
    destination: /data
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
  BeforeInstall:
    - location: scripts/packages.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3600
