version: 0.0
os: linux
files:
  - source: mongo
    destination: /etc/
  - source: data
    destination: /data
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
  BeforeInstall:
    - location: scripts/packages.sh
  AfterInstall:
    - location: scripts/gen_json.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
