version: 0.0
os: linux
files:
  - source: python
    destination: /data
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
  BeforeInstall:
    - location: scripts/packages.sh
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 10
